/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubes_pbo_1;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class Home extends javax.swing.JFrame {

    private DbUsers dbu;
    private DBDuit dbd;
    private DefaultTableModel incomeModel = new DefaultTableModel();
    private DefaultTableModel outcomeModel = new DefaultTableModel();
    /**
     * Creates new form Home
     */
    public Home(DbUsers dbu) throws SQLException {
        this.dbu = dbu;
        this.dbd = new DBDuit(dbu);
        initComponents();
        profilesButton.setText(dbu.getLoginProfile().getName());
        incomeModel.addColumn("Num");
        incomeModel.addColumn("Income Name");
        incomeModel.addColumn("Amount");
        incomeModel.addColumn("Yang Bertanggung Jawab");
        incomeModel.addColumn("TGL");
        incomeTable.setModel(incomeModel);
        populateIncomeTable(dbd);

        outcomeModel.addColumn("Num");
        outcomeModel.addColumn("Outcome Name");
        outcomeModel.addColumn("Amount");
        outcomeModel.addColumn("Yang Bertanggung Jawab");
        outcomeModel.addColumn("TGL");
        outcomeTable.setModel(outcomeModel);
        populateOutcomeTable(dbd);

        
        welcome1.setText("Welcome "+ dbu.getLoginProfile().getName()+" Your Amount Money Currently Is "+dbu.getUser().getAmount()+" USD. ");
    }
    public void populateIncomeTable(DBDuit dbd) throws SQLException{
        incomeModel.setRowCount(0);
        int counter = 1;
        ArrayList<Duit> income = dbd.getIncome();
        for (Duit d : income){
            Object [] addData = {counter++, d.getName(), d.getAmount()+" USD", d.getProfileName(), d.getDate()};
            incomeModel.addRow(addData);
        }
         welcome1.setText("Welcome "+ dbu.getLoginProfile().getName()+" Your Saldo Currently Is "+dbu.getUser().getAmount());
    }
    public void populateOutcomeTable(DBDuit dbd) throws SQLException{
        outcomeModel.setRowCount(0);
        int counter = 1;
        ArrayList<Duit> outcome = dbd.getOutcome();
        for (Duit d : outcome){
            Object [] addData = {counter++, d.getName(), d.getAmount()+" USD", d.getProfileName(), d.getDate()};
            outcomeModel.addRow(addData);
        }
        welcome1.setText("Welcome "+ dbu.getLoginProfile().getName()+" Your Saldo Currently Is "+dbu.getUser().getAmount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome1 = new javax.swing.JLabel();
        profilesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outcomeTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameIncomeField = new javax.swing.JTextField();
        amountIncomeField = new javax.swing.JTextField();
        submitIncome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameOutcomeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        amountOutcomeField = new javax.swing.JTextField();
        submitOutcome = new javax.swing.JButton();
        logoutButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome1.setText("jLabel1");
        welcome1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                welcome1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        profilesButton.setText("Profiles");
        profilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilesButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("LogOut");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(outcomeTable);

        jScrollPane2.setViewportView(incomeTable);

        jLabel1.setText("Income");

        jLabel2.setText("Outcome");

        submitIncome.setText("Add Income");
        submitIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitIncomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Amount");

        jLabel5.setText("Name");

        jLabel6.setText("Amount");

        submitOutcome.setText("Add Outcome");
        submitOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitOutcomeActionPerformed(evt);
            }
        });

        logoutButton1.setText("LogOut As Profile");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton)
                        .addGap(16, 16, 16)
                        .addComponent(logoutButton1)
                        .addGap(18, 18, 18)
                        .addComponent(profilesButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(amountIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitIncome)
                            .addComponent(nameOutcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(amountOutcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitOutcome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilesButton)
                    .addComponent(welcome1)
                    .addComponent(logoutButton)
                    .addComponent(logoutButton1))
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitIncome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameOutcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountOutcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitOutcome)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        login login = new login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void welcome1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_welcome1AncestorAdded
                // TODO add your handling code here:
    }//GEN-LAST:event_welcome1AncestorAdded

    private void profilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilesButtonActionPerformed
        try {
            ProfileConfig pf = new ProfileConfig(dbu);
            pf.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_profilesButtonActionPerformed

    private void submitIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitIncomeActionPerformed
        try {
            if(nameIncomeField.getText().equals("")||amountIncomeField.getText().equals("")){
                JOptionPane.showMessageDialog(this, "FILL THE FIELD BRUV!!!!");
            }
            if(dbd.addIncome(nameIncomeField.getText(), Double.parseDouble(amountIncomeField.getText()))){
                JOptionPane.showMessageDialog(this, "YOU'VE MADE AN INCOME!!!, YOU DID IT!!!");
                populateIncomeTable(dbd);
                nameIncomeField.setText("");
                amountIncomeField.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitIncomeActionPerformed

    private void submitOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitOutcomeActionPerformed
        try {
            if(dbd.addOutcome(nameOutcomeField.getText(), Double.parseDouble(amountOutcomeField.getText()))){
                JOptionPane.showMessageDialog(this, "YOU'VE MADE AN EXPENSES!!!, YOU BETTER MAKE AN INCOME OR ELSE U WILL GO BROKE!!!");
                populateOutcomeTable(dbd);
                nameOutcomeField.setText("");
                amountOutcomeField.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this, "YOU BROKE, MAKE SOME MONEY!!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitOutcomeActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        ProfileForm pf = new ProfileForm(dbu);
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountIncomeField;
    private javax.swing.JTextField amountOutcomeField;
    private javax.swing.JTable incomeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JTextField nameIncomeField;
    private javax.swing.JTextField nameOutcomeField;
    private javax.swing.JTable outcomeTable;
    private javax.swing.JButton profilesButton;
    private javax.swing.JButton submitIncome;
    private javax.swing.JButton submitOutcome;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
